import { Moment } from 'moment';

export interface User {
  avatar_url: string,
  bio: string,
  blog: string,
  company: string,
  created_at: Moment,
  email: string,
  events_url: string,
  followers_url: string,
  followers: number,
  following_url: string,
  following: number,
  gists_url: string,
  gravatar_id: string,
  hireable: string,
  html_url: string,
  id: number,
  location: string,
  login: string,
  name: string,
  node_id: string,
  organizations_url: string,
  public_gists: number,
  public_repos: number,
  received_events_url: string,
  repos_url: string,
  site_admin: false,
  starred_url: string,
  subscriptions_url: string,
  twitter_username: string,
  type: string,
  updated_at: Moment,
  url: string,
  user_view_type: string,
}